### ISSUE TITLE
[PE-D][Tester C] Phone number for user input can exceed 8 characters

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F13-4/tp#138]
When providing user input for phone number to create a new entry, the phone number section can exceed 8 characters (I provided 9).

![image.png](https://raw.githubusercontent.com/chngchngchng/ped/main/files/e654f7dd-d65f-465a-ab77-6706c407c66b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: chngchngchng/ped#1

**Comment by LolfoollorS** [comment]
I think this shouldn't be fixed since international number exist and it can exceed 8 numbers

**Comment by ou4jairmeiogusrjejiepr** [comment]
> I think this shouldn't be fixed since international number exist and it can exceed 8 numbers

Agreed, should we close this issue?

**Comment by LolfoollorS** [comment]
Okay
