### ISSUE TITLE
[PE-D][Tester D] Specificity of error message for invalid delete input

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F13-4/tp#143]
Error messages is correct but not specific enough. It says the input is 'invalid' without giving the reason (out of bounds of list)

![Screenshot 2022-10-28 at 4.24.05 PM.png](https://raw.githubusercontent.com/gnahzeus/ped/main/files/00e6ea9b-14fd-4c54-870f-ee33043bf103.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: gnahzeus/ped#5

**Comment by LolfoollorS** [comment]
The user does not need to know it is out of bounds

**Comment by LolfoollorS** [comment]
Hmm I know I put this as invalid but I thought about it and maybe it should be "Id should only contain one positive numeric character, and it should not be blank and below 99998!" this message instead?
