### ISSUE TITLE
[PE-D][Tester D] Frequent use of * in the callout code blocks 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F13-4/tp#161]
Frequent use of * in the callout code blocks (but intended markdown effect does not seem to be working). Instead, * is just displayed.

![Screenshot 2022-10-28 at 4.49.07 PM.png](https://raw.githubusercontent.com/gnahzeus/ped/main/files/a61703ae-f7a7-4661-82ff-a0d1a4fe3d6b.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: gnahzeus/ped#15

**Comment by xhphoong** [comment]
I think for some of them (the tip box) it is not fix, [userguide](https://ay2223s1-cs2103-f13-4.github.io/tp/UserGuide.html), I am fixing it now
