### ISSUE TITLE
[PE-D][Tester C] Not all data is saved when exiting and entering the application

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F13-4/tp#172]
The "attending physician" field for patients is not saved after the app is exited and re-entered. The unmark field is also not saved.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: chngchngchng/ped#5

**Comment by xhphoong** [comment]
Havent check whether the attending physician field got saved
