### ISSUE TITLE
As a medical administrator, I can add the unavailability of the nurse

### ISSUE THREAD

**Issue by johnbenedictyan** [AY2223S1-CS2103-F13-4/tp#84]
so that I can use this information to assign the patient to them.

**Comment by xhphoong** [comment]
Actually hmm after thinking, is it better if can add unavailability instead of availability? cuz the day that is unavailable is usually less than the day available?

**Comment by ou4jairmeiogusrjejiepr** [comment]
> Actually hmm after thinking, is it better if can add unavailability instead of availability? cuz the day that is unavailable is usually less than the day available?

Sure
