### ISSUE TITLE
As a medical administrator, I can know that a patient's timeslot is scheduled or not,

### ISSUE THREAD

**Issue by johnbenedictyan** [AY2223S1-CS2103-F13-4/tp#92]
so that if the patient changes the date for the home visit, I will remember to schedule the patient again/ so that if I know which timeslot I have not scheduled.

**Comment by xhphoong** [comment]
I change it like this because I think we do not need the medical admin to mark or unmark manually ? We will just mark or unmark (in the behind scene) then we display it for the medical admin?  Is it ok?

**Comment by ou4jairmeiogusrjejiepr** [comment]
> I change it like this because I think we do not need the medical admin to mark or unmark manually ? We will just mark or unmark (in the behind scene) then we display it for the medical admin? Is it ok?

yup that's fine
